export const TRANSACTION_TYPES = {
  GASTO: "GASTO",
  INGRESO: "INGRESO",
  TRANSFERENCIA_ENTRADA: "TRANSFERENCIA_ENTRADA",
  TRANSFERENCIA_SALIDA: "TRANSFERENCIA_SALIDA",
  AJUSTE: "AJUSTE"
} as const;

export const transactionTypeLabels: Record<string, string> = {
  [TRANSACTION_TYPES.AJUSTE]: "AJUSTE",
  [TRANSACTION_TYPES.GASTO]: "GASTO",
  [TRANSACTION_TYPES.INGRESO]: "INGRESO",
  [TRANSACTION_TYPES.TRANSFERENCIA_ENTRADA]: "TRANSFERENCIA_ENTRADA",
  [TRANSACTION_TYPES.TRANSFERENCIA_SALIDA]: "TRANSFERENCIA_SALIDA"
};